# Generated by Django 3.2.5 on 2021-11-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_followings',
            field=models.IntegerField(default=0),
        ),
    ]
